apiVersion: v1
kind: Secret
metadata:
  name: dify-api-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  CELERY_BROKER_URL: {{ printf "redis://:%s@redis:6379/0" .Values.redis.password | quote }}
  CELERY_BROKER_URL_DB1: {{ printf "redis://:%s@redis:6379/1" .Values.redis.password | quote }}
  SMTP_PASSWORD: {{ .Values.olaresEnv.SMTP_PASSWORD | default "password" | quote }}
  SECRET_KEY: "olares-difyv3-secret-key-please-rotate-42"
