---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: sickchill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sickchill
  template:
    metadata:
      labels:
        app: sickchill
    spec:
      containers:
      - name: sickchill
        image: sickchill/sickchill:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /data
          name: sickchill-config
          subPath: data
        - mountPath: /downloads
          name: sickchill-config
          subPath: downloads
        - mountPath: /tv
          name: sickchill-config
          subPath: tv
      volumes:
      - name: sickchill-config
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appdata }}/sickchill 
        

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
