---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cosyvoice-config
  namespace: {{ .Release.Namespace }}
data:
  CDN_HOST: "{{ .Values.downloadCdnURL | default "https://cdn.joinolares.cn" }}/models"
  INIT_MODELS: "CosyVoice-300M"