---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    upstream app_backend {
        server doclingservev2.doclingservev2server-shared:5001 max_fails=1 fail_timeout=2s;
    }

    server {
        listen 8080;
        access_log /opt/bitnami/openresty/nginx/logs/access.log;
        error_log /opt/bitnami/openresty/nginx/logs/error.log;

        # Support large file uploads (100MB)
        client_max_body_size 100m;

        proxy_connect_timeout 300s;
        proxy_send_timeout 600s;
        proxy_read_timeout 1800s;

        proxy_set_header host $host;
        proxy_set_header x-forwarded-host $http_host;
        proxy_set_header x-real-ip $remote_addr;
        proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;

        # Force HTTPS protocol
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Scheme https;

        proxy_http_version 1.1;
        proxy_set_header upgrade $http_upgrade;
        proxy_set_header connection "upgrade";
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_request_headers on;

        # API endpoints without /v1 prefix
        location = /version {
            proxy_pass http://app_backend/version;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        location = /health {
            proxy_pass http://app_backend/health;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        # v1 API endpoints
        location /v1/ {
            proxy_pass http://app_backend;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        # Docs and OpenAPI
        location /docs {
            proxy_pass http://app_backend;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        location ~ ^/(openapi\.json|docs/openapi\.json)$ {
            proxy_pass http://app_backend;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        # UI
        location /ui {
            proxy_pass http://app_backend;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }

        # Default route - redirect to UI
        location / {
            proxy_pass http://app_backend/ui;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 1800s;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: doclingservev2ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: doclingservev2ingress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: doclingservev2ingress
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: nginx
          image: docker.io/beclab/aboveos-bitnami-openresty:1.25.3-2
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OPENRESTY_CONF_FILE
              value: /etc/nginx/nginx.conf
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
                  [ $http_code -ge 200 ] && [ $http_code -lt 500 ]
            initialDelaySeconds: 2
            timeoutSeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 60
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks/nginx.conf
              subPath: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: doclingservev2ingress
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    io.kompose.service: doclingservev2ingress
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
