apiVersion: v1
kind: ConfigMap
metadata:
  name: nzbget-defaults
  namespace: {{ .Release.Namespace }}
data:
  # Olares path overrides applied to nzbgetcom template on first install.
  # See https://github.com/nzbgetcom/nzbget/blob/develop/nzbget.conf#L4
  nzbget-overrides.conf: |
    MainDir=/config
    DestDir=/olares/userdata/home/Downloads/nzbget
    InterDir=/olares/userdata/home/Downloads/nzbget/inter
    NzbDir=/config/nzb
    QueueDir=/config/queue
    TempDir=/config/tmp
    ScriptDir=/config/scripts
    LockFile=/config/nzbget.lock
    LogFile=/config/nzbget.log
