apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: photoview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoview
  template:
    metadata:
      labels:
        app: photoview
    spec:
      containers:
      - name: photoview
        image: aboveos/viktorstrate-photoview:2
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: PHOTOVIEW_DATABASE_DRIVER
          value: mysql
        - name: PHOTOVIEW_LISTEN_IP
          value: 0.0.0.0
        - name: PHOTOVIEW_LISTEN_PORT
          value: "8080"
        - name: PHOTOVIEW_MEDIA_CACHE
          value: /app/cache
        - name: PHOTOVIEW_MYSQL_URL
          value: '{{ .Values.mariadb.username}}:{{ .Values.mariadb.password}}@tcp({{ .Values.mariadb.host }}:3306)/{{ .Values.mariadb.databases.photoview }}'
        volumeMounts:
        - name: cache
          mountPath: /app/cache
        - name: photos
          mountPath: /photos
          readOnly: true
        - name: user-data
          mountPath: /data
       
      volumes:
      - name: cache
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/photoview
      - name: photos
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/photoview/photos
      - name: user-data
        hostPath:
          type: Directory
          path: {{ .Values.userspace.userData }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: phtoviewtcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      