apiVersion: v1
kind: ConfigMap
metadata:
  name: koboldcpp-env
  namespace: {{ .Release.Namespace }}
data:
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  KCPP_MODEL: ""
  KCPP_ARGS: "--model /models/qwen2.5-1.5b-instruct-q4_k_m.gguf --contextsize 4096"
  KCPP_DONT_UPDATE: "true"
  KCPP_DONT_TUNNEL: "true"
  KCPP_DONT_REMOVE_MODELS: "true"
