source_url: https://huggingface.co/NeverSleep/Noromaid-7b-v0.1.1-GGUF/resolve/main/Noromaid-7b-v0.1.1.q5_k_m.gguf
id: noromaid7b
object: model
name: Noromaid 7B Q5
version: '1.0'
description: Llama 2 Chat 7b model, specifically designed for a comprehensive understanding
  through training on extensive internet data.
format: gguf
settings:
  ctx_len: 4096
  prompt_template: |-
    ### Instruction:{prompt}
    ### Response:
parameters:
  temperature: 0.7
  top_p: 0.95
  stream: true
  max_tokens: 4096
  stop: []
  frequency_penalty: 0
  presence_penalty: 0
metadata:
  author: NeverSleep
  tags:
  - 7B
  - Merged
  size: 4370000000
engine: nitro