apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: olares-cli chart from-compose --name audiovoicestudiov3 --title
      Voice Studio V3 --new-schema -f audiovoicestudiov3-compose.yml -o ./audiovoicestudiov3
    kompose.version: 1.30.0 (HEAD)
    olares.service.type: Entrance
  labels:
    io.kompose.service: web
  name: web
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: "3900"
    port: 3900
    targetPort: 3900
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
