{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostream
  namespace: {{ .Release.Namespace }}
  labels:
    app: nostream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostream
  template:
    metadata:
      labels:
        app: nostream
    spec:
      initContainers:
      - name: init-nostream-data
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          mkdir -p /home/node/.nostr && \
          touch /home/node/.nostr/settings.yaml && \
          chown -R 1000:1000 /home/node/.nostr
        volumeMounts:
        - name: nostream-config
          mountPath: /home/node/.nostr
      containers:
      - name: nostream
        image: "ghcr.io/cameri/nostream:v2.1.0"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        env:
        - name: SECRET
          value: "changeme"
        - name: RELAY_PORT
          value: "8008"
        - name: NOSTR_CONFIG_DIR
          value: "/home/node/.nostr"
        - name: DB_USER
          value: "{{ .Values.postgres.username }}"
        - name: DB_PASSWORD
          value: "{{ .Values.postgres.password }}"
        - name: DB_NAME
          value: "{{ .Values.postgres.databases.nostream }}"
        - name: DB_HOST
          value: {{ .Values.postgres.host }}
        - name: DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: REDIS_USER
          value: "default"
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}
        ports:
        - containerPort: 8008
        volumeMounts:
        - name: nostream-config
          mountPath: /home/node/.nostr
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: nostream-config
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nostream
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: nostream
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008

---
apiVersion: v1
kind: Service
metadata:
  name: sharedentrances-nostream
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: ws
    port: 80
    targetPort: 8008
  selector:
    app: nostream
{{- end }}
