apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate         
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: init-chmod-data
        image: 'docker.io/aboveos/busybox:latest'
        command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /appcache
        resources: {}
        volumeMounts:
          - name:  appcache
            mountPath: /appcache
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      containers:
      - name: redis
        image: valkey/valkey:8
        command: ["redis-server", "--requirepass", "infini_rag_flow", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 512Mi
      volumes:
      - hostPath:
          path: '{{ .Values.userspace.appCache }}/ragflow'
          type: DirectoryOrCreate
        name: appcache
      - hostPath:
          path: '{{ .Values.userspace.appCache }}/ragflow/redis'
          type: DirectoryOrCreate
        name: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis