apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: mins-router-catalog-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: mins
  appNamespace: router
  middleware: nats
  nats:
    user: {{ printf "%s-mins-catalog" .Release.Namespace | quote }}
    password:
      valueFrom:
        secretKeyRef:
          name: mins-nats
          key: password
    subjects:
      - name: catalog
        permission:
          pub: deny
          sub: allow
---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: mins-user-directory-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: mins-users
  appNamespace: os
  middleware: nats
  nats:
    user: {{ printf "%s-mins-users" .Release.Namespace | quote }}
    password:
      valueFrom:
        secretKeyRef:
          name: mins-nats
          key: password
    subjects:
      - name: users
        permission:
          pub: deny
          sub: allow
      - name: groups
        permission:
          pub: deny
          sub: allow
