binary:
  source: image
  inImagePath: /app/note

runtimeImage:
  repository: docker.io/linuxserver/ffmpeg
  tag: "9.0-cli-ls78"

appImage:
  repository: "docker.io/olareshzy/note"
  tag: "2.0.45-8d5d7acf"

imagePullPolicy: IfNotPresent

dataDirName: note

workloads:
  note:
    replicaCount: 1

postgres:
  host: localhost
  port: 5432
  username: note
  password: ""
  databases:
    note: note

userspace:
  appData: /tmp/note-appdata
  appCache: /tmp/note-appcache

user:
  zone: ""
