apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-router
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-key: {{ .Values.olaresEnv.DINA_ROUTER_API_KEY | default "" | quote }}
