apiVersion: v1
kind: Service
metadata:
  name: lares
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: lares
spec:
  ports:
  - name: http
    port: 30141
    targetPort: 30141
    protocol: TCP
  selector:
    io.kompose.service: lares
