


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdlp-provider
  namespace: {{ .Release.Namespace }}
  labels:
    app: ytdlp-provider
    applications.app.bytetrade.io/author: bytetrade.io
    provider: 'true'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ytdlp-provider
  template:
    metadata:
      labels:
        app: ytdlp-provider
    spec:
      containers:
        - name: provider-proxy
          image: beclab/provider-proxy:0.1.0
          imagePullPolicy: IfNotPresent
          args:
          - --logtostderr
          - --insecure-listen-address=:28080
          - --upstream=http://ytdlp-svc:3082/
          ports:
          - containerPort: 28080
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: "500m"
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ytdlp-provider-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: ytdlp-provider
  ports:
    - name: server
      protocol: TCP
      port: 28080
      targetPort: 28080
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:{{ .Release.Namespace }}:ytdlp-provider
  annotations:
    provider-registry-ref: '{{ .Release.Namespace }}/ytdlp-provider'
    provider-service-ref: 'ytdlp-provider.{{ .Release.Namespace }}:28080'
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]