{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $ollamaclientDomainENV := split "," .Values.domain.ollamaclient -}}
{{- $ollamaclientDomain := index $ollamaclientDomainENV "_0" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ollamabgem3567m
  name: ollamabgem3567m
  namespace: "{{ .Release.Namespace }}"
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ollamabgem3567m
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: ollamabgem3567m
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.12.7
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: GGML_CUDA_DISABLE_GRAPHS
              value: "1"
            - name: OLLAMA_ORIGINS
              value: "*"
          ports:
            - containerPort: 11434
          livenessProbe:
            httpGet:
              path: /
              port: 11434
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            tcpSocket:
              port: 11434
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          resources:
            limits:
              cpu: "4"
              memory: 30Gi
            requests:
              cpu: 50m
              memory: 4Gi
          volumeMounts:
            - mountPath: "/root/.ollama"
              name: data
        - name: api
          image: harveyff/olares-ollama:v0.0.3
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DISPLAY
              value: ":0"
            - name: OLLAMA_MODEL
              value: "bge-m3:567m"
            - name: OLLAMA_URL
              value: "http://localhost:11434"
            - name: APP_URL
              value: "http://{{ $ollamaclientDomain }}"
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: data
          hostPath:
            path: "{{ .Values.userspace.userData }}/Ollama/{{ .Release.Name }}"
            type: DirectoryOrCreate
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: "api"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: ollamabgem3567m
status:
  loadBalancer: {}

{{- end }}