apiVersion: v1
kind: Service
metadata:
  name: damoradar
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: damoradar
  ports:
    - name: http
      port: 8080
      targetPort: http
