apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-env
  namespace: {{ .Release.Namespace }}
data:
  OLLAMA_ORIGINS: "*"
  OLLAMA_FLASH_ATTENTION: "1"
  OLLAMA_MAX_LOADED_MODELS: "1"
  LLAMA_ARG_FIT: "on"
  LLAMA_ARG_FIT_TARGET: "1024"
