
apiVersion: v1
data:
  nginx.conf: |
      server {

        listen 8080;
        access_log /opt/bitnami/openresty/nginx/logs/access.log;
        error_log /opt/bitnami/openresty/nginx/logs/error.log;

        proxy_connect_timeout                          30s;
        proxy_send_timeout                             60s;
        proxy_read_timeout                             300s;
        proxy_set_header      host                      $host;
        proxy_set_header      x-forwarded-host          $http_host;

        proxy_http_version 1.1;

        proxy_set_header upgrade $http_upgrade;
        proxy_set_header connection "upgrade";

        location / {
            resolver coredns.kube-system.svc.cluster.local valid=10s;
            proxy_pass http://stablefast3dshare.stablefast3dshare-{{ .Values.admin }}:7860;
            add_header X-Frame-Options "";
            proxy_next_upstream error timeout http_502 http_503 http_504 http_403;
            proxy_next_upstream_tries 3;
        }
      }

kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: stablefast3dclient
{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
  name: stablefast3dclient
{{- else }}
  name: stablefast3dshare
{{- end }}
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stablefast3dclient
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: stablefast3dclient
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 438
            items:
            - key: nginx.conf
              path: nginx.conf
      containers:
        - name: nginx
          image: docker.io/aboveos/bitnami-openresty:1.25.3-2
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OPENRESTY_CONF_FILE
              value: /etc/nginx/nginx.conf
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks/nginx.conf
              subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: stablefast3dclient
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: stablefast3dclient
  ports:
    - name: stablefast3dclient
      protocol: TCP
      port: 8080
      targetPort: 8080
