{{- $app_secret := (lookup "v1" "Secret" .Release.Namespace "crawl4ai") -}}
{{- $api_token := "" -}}
{{ if $app_secret -}}
  {{- $api_token = (index $app_secret "data" "api-token") | b64dec -}}
{{ else -}}
  {{- $api_token = randAlphaNum 32 -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: crawl4ai
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-token: {{ $api_token }}
