apiVersion: v1
kind: Service
metadata:
  name: mempalace
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: mempalace
spec:
  ports:
    - name: mcp
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: mempalace
