apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-config 
  namespace: {{ .Release.Namespace }}
data:
  domain.conf: |
    {
      "_config": {
        "_blackurls": [
          "https://example.com/blacklisted.html"
        ]
      },
      "apnews.com": {
        "isBlacklist": "/^https://(www\\.)?apnews\\.com/live/.*$/"
      },
      "barrons.com": {
        "isBlacklist": ""
      },
      "bbc.com": {
        "isBlacklist": "/^https://(www\\.)?bbc\\.com/(?:.*/)?(audio|live)/.*$/"
      },
      "bilibili.com": {
        "skipUploadHtml": true,
        "isBlacklist": "/^(https?://)?((live\\.|manga\\.|cheese\\.)bilibili\\.com(/.*)?|([a-zA-Z0-9-]+\\.)*bilibili\\.com/cheese(/.*)?)$/",
        "cookie": "required",
        "ytdlp": true,
        "fetchMode": "http"
      },
      "bloomberg.com": {
        "isBlacklist": ""
      },
      "buzzsprout.com": {
        "isBlacklist": ""
      },
      "cnbc.com": {
        "isBlacklist": "/^https://(www\\.)?cnbc\\.com/video(/.*)?$/"
      },
      "cnn.com": {
        "isBlacklist": "/^https://edition\\.cnn\\.com/audio/.*$/"
      },
      "dailymail.co.uk": {
        "isBlacklist": "/^https://(www\\.)?dailymail\\.co\\.uk/video(/.*)?$/"
      },
      "douyin.com": {
        "isBlacklist": ""
      },
      "euronews.com": {
        "isBlacklist": ""
      },
      "facebook.com": {
        "isBlacklist": ""
      },
      "instagram.com": {
        "isBlacklist": ""
      },
      "marketwatch.com": {
        "isBlacklist": ""
      },
      "newsweek.com": {
        "isBlacklist": ""
      },
      "nypost.com": {
        "isBlacklist": "/^https://(www\\.)?nypost\\.com/video(/.*)?$/"
      },
      "olares.cn": {
        "isBlacklist": "/^https?://[^./]+\\.[^./]+\\.olares\\.cn(/.*)?$/"
      },
      "olares.com": {
        "isBlacklist": "/^https?://[^./]+\\.[^./]+\\.olares\\.com(/.*)?$/"
      },
      "olares.local": {
        "isBlacklist": "/^https?://[^./]+\\.[^./]+\\.olares\\.local(/.*)?$/"
      },
      "open.spotify.com": {
        "isBlacklist": ""
      },
      "pinterest.com": {
        "isBlacklist": ""
      },
      "pornhub.com": {
        "skipUploadHtml": true,
        "ytdlp": true,
        "fetchMode": "skip"
      },
      "rfi.fr": {
        "isBlacklist": ""
      },
      "reuters.com": {
        "isBlacklist": ""
      },
      "spreaker.com": {
        "isBlacklist": ""
      },
      "theguardian.com": {
        "isBlacklist": "/^https://(www\\.)?theguardian\\.com/.*/(audio|video|live)/.*$/"
      },
      "threads.com": {
        "isBlacklist": "",
        "blockMedia": false,
        "fetchMode": "headless",
        "headlessAction": [
          {
            "type": "wait",
            "milliseconds": 2000
          },
          {
            "type": "scroll"
          },
          {
            "type": "wait",
            "milliseconds": 2000
          }
        ]
      },
      "tiktok.com": {
        "isBlacklist": ""
      },
      "usatoday.com": {
        "isBlacklist": ""
      },
      "usnews.com": {
        "isBlacklist": ""
      },
      "washingtonpost.com": {
        "isBlacklist": ""
      },
      "wsj.com": {
        "isBlacklist": ""
      },
      "x.com": {
        "isBlacklist": "/^https://(www\\.)?x\\.com/i/trending/\\d+$/,/^https://(www\\.)?x\\.com/i/events/\\d+$/",
        "cookie": "required",
        "fetchMode": "skip"
      },
      "xiaohongshu.com": {
        "isBlacklist": ""
      },
      "xhslink.com": {
        "isBlacklist": ""
      },
      "youtube.com": {
        "skipUploadHtml": true,
        "isBlacklist": "/^(https?://)?(music\\.youtube\\.com(/.*)?|(www\\.)?youtube\\.com/((post|live)(/.*)?|@[^/?#]+/live([/?#].*)?))$/",
        "ytdlp": true,
        "fetchMode": "skip"
      },
      "youtubekids.com": {
        "isBlacklist": ""
      },
      "threads.net": {
        "blockMedia": false,
        "fetchMode": "headless",
        "headlessAction": [
          {
            "type": "wait",
            "milliseconds": 2000
          },
          {
            "type": "scroll"
          },
          {
            "type": "wait",
            "milliseconds": 2000
          }
        ]
      },
      "quora.com": {
        "fetchMode": "headless",
        "headlessAction": [
          {
            "type": "wait",
            "milliseconds": 2000
          },
          {
            "type": "scroll"
          }
        ]
      },
      "ximalaya.com": {
        "headlessWaitFor": "meta[name=\"robots\"][data-react-helmet=\"true\"]",
        "fetchMode": "headless"
      },
      "medium.com": {
        "fetchMode": "headless"
      },
      "nytimes.com": {
        "fetchMode": "headless"
      },
      "people.com": {
        "fetchMode": "headless"
      },
      "reddit.com": {
        "fetchMode": "headless"
      },
      "twitter.com": {
        "cookie": "required",
        "fetchMode": "skip"
      }
    }
