---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vc-gateway-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream backend {
            server {{ .Release.Name }}-svc:6000;
        }
        
        server {
            listen 8080;
            
            # Add HTTP/2 and protocol upgrade support
            location /api/grpc/AuthService/ActivateAndGrant {
                rewrite ^/api(.*)$ $1 break;
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";
                proxy_http_version 1.1;
            }
            
            location /api/grpc/AuthService/GetApplicationSchema {
                rewrite ^/api(.*)$ $1 break;
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";
                proxy_http_version 1.1;
            }
            
            location /api/grpc/BlockchainService/LaresPassRsaKeyCallback {
                rewrite ^/api(.*)$ $1 break;
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";
                proxy_http_version 1.1;
            }
            
            location /api/grpc/KeyManageService/SubmitPrivateKey {
                rewrite ^/api(.*)$ $1 break;
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";
                proxy_http_version 1.1;
            }
            

            
            location / {
                return 204;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vc-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: vc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-gateway
  template:
    metadata:
      labels:
        app: vc-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-vc-gateway-nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: vc-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: vc-gateway
  ports:
    - name: http
      port: 6005
      targetPort: 8080
      protocol: TCP