terminusManifest.version: '0.7.0'
terminusManifest.type: app
metadata:
  name: prometheus
  description: From metrics to insight
  icon: https://file.bttcdn.com/appstore/prometheus/icon.png
  appid: prometheus
  version: 0.0.3
  title: Prometheus
  categories:
  - Utilities
permission:
  appData: true
  appCache: true
spec:
  versionName: '2.54.1'
  fullDescription: |
    Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts when specified conditions are observed.

    The features that distinguish Prometheus from other metrics and monitoring systems are:
    - A multi-dimensional data model (time series defined by metric name and set of key/value dimensions)
    - PromQL, a powerful and flexible query language to leverage this dimensionality
    - No dependency on distributed storage; single server nodes are autonomous
    - An HTTP pull model for time series collection
    - Pushing time series is supported via an intermediary gateway for batch jobs
    - Targets are discovered via service discovery or static configuration
    - Multiple modes of graphing and dashboarding support
    - Support for hierarchical and horizontal federation
  upgradeDescription: |
    [BUGFIX] Scraping: allow multiple samples on same series, with explicit timestamps. #14685
    [BUGFIX] Docker SD: fix crash in match_first_network mode when container is reconnected to a new network. #14654
    [BUGFIX] PromQL: fix experimental native histogram counter reset detection on stale samples. #14514
    [BUGFIX] PromQL: fix experimental native histograms getting corrupted due to vector selector bug in range queries. #14538
    [BUGFIX] PromQL: fix experimental native histogram memory corruption when using histogram_count or histogram_sum. #14605
    Check the full release note at: https://github.com/prometheus/prometheus/releases/tag/v2.54.1

  developer: Prometheus
  website: https://prometheus.io/
  sourceCode: https://github.com/prometheus/prometheus
  submitter: Terminus
  language:
  - en
  doc: https://prometheus.io/docs/introduction/overview/
  license:
  - text: Apache-2.0
    url: https://github.com/prometheus/prometheus#Apache-2.0-1-ov-file
  requiredMemory: 32Mi
  limitedMemory: 64Mi
  requiredDisk: 128Mi
  limitedDisk: 256Mi
  requiredCpu: 100m
  limitedCpu: 200m
  supportArch:
  - amd64
options:
  dependencies:
  - name: terminus
    type: system
    version: '>=1.8.0-0'
entrances:
- name: astral-svc
  port: 8000
  host: astral-svc
  title: Astral
  icon: https://file.bttcdn.com/appstore/prometheus/icon.png
