source_url: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf
id: mistralins7bq4
object: model
name: Mistral Instruct 7B Q4
version: '1.0'
description: Mistral Instruct 7b model, specifically designed for a comprehensive understanding through training on extensive internet data.
format: gguf
settings:
  ctx_len: 4096
  prompt_template: |-
    [INST] <<SYS>>
    {system_message}<</SYS>>
    {prompt}[/INST]
parameters:
  temperature: 0.7
  top_p: 0.95
  stream: true
  max_tokens: 4096
  stop: []
  frequency_penalty: 0
  presence_penalty: 0
metadata:
  author: MistralAI, The Bloke
  tags:
  - 7B
  - Foundational Model
  size: 4370000000
engine: nitro