{{- $namespace := printf "%s" "knowledge-shared" -}}
{{- $rss_secret := (lookup "v1" "Secret" $namespace "rss-secrets") -}}
{{- $password := "" -}}
{{ if $rss_secret -}}
{{ $password = (index $rss_secret "data" "pg_password") }}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}

{{- $redis_password := "" -}}
{{ if $rss_secret -}}
{{ $redis_password = (index $rss_secret "data" "redis_password") }}
{{ else -}}
{{ $redis_password = randAlphaNum 16 | b64enc }}
{{- end -}}


{{- $redis_password_data := "" -}}
{{ $redis_password_data = $redis_password | b64dec }}

{{- $pg_password_data := "" -}}
{{ $pg_password_data = $password | b64dec }}

{{- $pg_user :=  printf "%s" "argo_os_framework" -}}
{{- $pg_user = $pg_user | b64enc -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: rss-secrets
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pg_user: {{ $pg_user }}
  pg_password: {{ $password }}
  redis_password: {{ $redis_password }}

---

apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: rss-pg
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
spec:
  app: rss
  # appNamespace: knowledge-shared
  appNamespace: {{ .Release.Namespace }}
  middleware: postgres
  postgreSQL:
    user: argo_os_framework
    password: 
      valueFrom:
        secretKeyRef:
          key: pg_password
          name: rss-secrets
    databases:
    - name: argo





    