

---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow-log-fakes3
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: S3RVER
  AWS_SECRET_ACCESS_KEY: S3RVER

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-rolebinding
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    # namespace: knowledge-shared
    namespace: {{ .Release.Namespace }}
    name: default
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io