apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoworkflow-workflow-controller
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: workflow-controller
    applications.app.bytetrade.io/author: bytetrade.io
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argoworkflows-workflow-controller
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: v3.5.0
    helm.sh/chart: argoworkflows-0.35.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: argo
      app.kubernetes.io/name: argoworkflows-workflow-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: workflow-controller
        app.kubernetes.io/instance: argo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: argoworkflows-workflow-controller
        app.kubernetes.io/part-of: argo-workflows
        app.kubernetes.io/version: v3.5.0
        helm.sh/chart: argoworkflows-0.35.0
    spec:
      serviceAccountName: argoworkflow-workflow-controller
      serviceAccount: argoworkflow-workflow-controller
      schedulerName: default-scheduler
      containers:
        - name: controller
          image: quay.io/argoproj/workflow-controller:v3.5.0
          imagePullPolicy: IfNotPresent
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "argoworkflow-workflow-controller-configmap"
          - "--executor-image"
          - "quay.io/argoproj/argoexec:v3.5.0"
          - "--loglevel"
          - "debug"
          - "--gloglevel"
          - "0"
          - "--log-format"
          - "text"
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          env:
            - name: ARGO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:	
            requests:	
              cpu: 10m	
              memory: 20Mi	
            limits:	
              cpu: "100m"	
              memory: 100Mi          
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          livenessProbe: 
            httpGet:
              path: /healthz
              port: 6060
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3

      nodeSelector:
        kubernetes.io/os: linux
      
     
