apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argoworkflow-workflow
  # namespace: knowledge-shared
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argoworkflow-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    # namespace: knowledge-shared
    namespace: {{ .Release.Namespace }}
