services:
  genoffice:
    image: harveyff/genoffice:v0.0.2
    ports:
      - "3000:3000"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      TITLE: GenOffice
    shm_size: "1gb"
    labels:
      olares.service.type: Entrance
    volumes:
      - config:/config
volumes:
  config:
