source_url: https://huggingface.co/janhq/stealth-v1.3-GGUF/resolve/main/stealth-v1.3.Q4_K_M.gguf
id: stealth7b
object: model
name: Stealth 7B Q4
version: '1.0'
description: This is a new experimental family designed to enhance Mathematical and Logical abilities..
format: gguf
settings:
  ctx_len: 4096
  prompt_template: |-
    <|im_start|>system
    {system_message}<|im_end|>
    <|im_start|>user
    {prompt}<|im_end|>
    <|im_start|>assistant
parameters:
  temperature: 0.7
  top_p: 0.95
  stream: true
  max_tokens: 4096
  stop: []
  frequency_penalty: 0
  presence_penalty: 0
metadata:
  author: Jan
  tags:
  - 7B
  - Finetuned
  size: 4370000000
engine: nitro