apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:{{ .Release.Name }}:llmgateway-provider
  annotations:
    provider-registry-ref: "{{ .Release.Name }}/llmgateway-provider"
    provider-service-ref: "llmgateway-provider.{{ .Release.Name }}:28080"
rules:
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:{{ .Release.Name }}:sa:default:llmgateway
rules:
  - apiGroups:
      - "*"
    resources:
      - users
    verbs:
      - list
      - watch
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend:{{ .Release.Name }}:sa:default:llmgateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend:{{ .Release.Name }}:sa:default:llmgateway
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
