apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose -f ../compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
    applications.app.bytetrade.io/gpu-inject: "true"
  labels:
    io.kompose.service: app
  name: app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose -f ../compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - name: app
          image: ghcr.io/zhongl/topdown:latest
          args:
            - -RenderOffscreen
            - -PixelStreamingURL=ws://signalling:8888
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 4
              memory: 16Gi          
      restartPolicy: Always
