apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
  labels:
    io.kompose.service: dman
  name: dman
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dman
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dman
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      initContainers:
        - name: init-permissions
          image: "docker.io/aboveos/busybox:1.37.0"
          command:
            - sh
            - -c
            - |
              mkdir -p /saved-data
              chown -R 1000:1000 /saved-data || true
              chmod -R 777 /saved-data || true
          volumeMounts:
            - name: saved-data
              mountPath: /saved-data
          securityContext:
            runAsUser: 0
      containers:
        - name: dman
          image: ghcr.io/zhongl/topdown:latest
          workingDir: /home/ue4/app/TopDown/Binaries/Linux
          args:
            - -RenderOffscreen
            - -PixelStreamingURL=ws://signalling:8888
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,graphics,utility,video,display"
            - name: DISPLAY
              value: ':0'
            - name: TZ
              value: Etc/UTC
            - name: HOME
              value: /home/ue4
            - name: VK_ICD_FILENAMES
              value: /usr/share/vulkan/icd.d/nvidia_icd.json
            - name: VK_LAYER_PATH
              value: /usr/share/vulkan/explicit_layer.d
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 8
              memory: 64Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: app-data
              mountPath: /appdata
            - name: saved-data
              mountPath: /home/ue4/app/TopDown/Saved
            - name: dev-dri
              mountPath: /dev/dri
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: app-data
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: {{ .Values.userspace.appData }}
              {{- else }}
            path: {{ .Values.userspace.appData }}/dman
              {{- end }}
            {{- else }}
            path: {{ .Values.userspace.appData }}/dman
            {{- end }}
        - name: saved-data
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: {{ .Values.userspace.appData }}/dman-saved
              {{- else }}
            path: {{ .Values.userspace.appData }}/dman/dman-saved
              {{- end }}
            {{- else }}
            path: {{ .Values.userspace.appData }}/dman/dman-saved
            {{- end }}
        - name: dev-dri
          hostPath:
            path: /dev/dri
