apiVersion: v1
kind: Service
metadata:
  name: chain-client-evm-eth-server-60
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: chain-client-evm-eth-60
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-evm-eth-api-60
      port: 9100
      targetPort: 9100
---
# Source: chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-evm-eth-60
  namespace: {{ .Release.Namespace }}
  labels:
    app: chain-client-evm-eth-60
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-evm-eth-60
  template:
    metadata:
      labels:
        app: chain-client-evm-eth-60
    spec:
      containers:
        - name: chain-client-evm-eth-60
          image: otmoic/otmoic-chainclient-evm:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 1024Mi
          ports:
            - containerPort: 9100
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "chain-client-status-report-eth"
            - name: CHAIN_TYPE
              value: "evm"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SYSTEM_CHAIN_ID
              value: "60"
            - name: CHAIN_ID
              value: "11155111"
            - name: OS_API_KEY
              value: {{ .Values.os.appKey }}
            - name: OS_API_SECRET
              value: {{ .Values.os.appSecret }}
            - name: OS_SYSTEM_SERVER
              value: system-server.user-system-{{ .Values.bfl.username }}
            - name: CONTRACT_ADDRESS
              value: "0xD6b2815Dc445e69aFbA7924f9744875FF2509Db2"
            - name: START_BLOCK
              value: "0"
            - name: RPC_URL
              value: "https://eth-sepolia-public.unifra.io"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: 'false'
