apiVersion: v1
kind: Service
metadata:
  name: chain-client-evm-avax-server-9000
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: chain-client-evm-avax-9000
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-evm-avax-api-9000
      port: 9100
      targetPort: 9100
---
# Source: chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-evm-avax-9000
  namespace: {{ .Release.Namespace }}
  labels:
    app: chain-client-evm-avax-9000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-evm-avax-9000
  template:
    metadata:
      labels:
        app: chain-client-evm-avax-9000
    spec:
      containers:
        - name: chain-client-evm-avax-9000
          image: otmoic/otmoic-chainclient-evm:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 1024Mi
          ports:
            - containerPort: 9100
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "chain-client-status-report-avax"
            - name: CHAIN_TYPE
              value: "evm"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SYSTEM_CHAIN_ID
              value: "9000"
            - name: CHAIN_ID
              value: "43113"
            - name: OS_API_KEY
              value: {{ .Values.os.appKey }}
            - name: OS_API_SECRET
              value: {{ .Values.os.appSecret }}
            - name: OS_SYSTEM_SERVER
              value: system-server.user-system-{{ .Values.bfl.username }}
            - name: CONTRACT_ADDRESS
              value: "0x1016A0886b4AeD69043367d501a99cfBAaB052B5"
            - name: START_BLOCK
              value: "0"
            - name: RPC_URL
              value: "https://avalanche-fuji.blockpi.network/v1/rpc/public"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: 'false'
