apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-evm-bsc-server-9006
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: obridge-chain-client-evm-bsc-9006
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-evm-bsc-api-9006
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-evm-bsc-9006
  namespace: {{ .Release.Namespace }}
  labels:
    app: obridge-chain-client-evm-bsc-9006
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-evm-bsc-9006
  template:
    metadata:
      labels:
        app: obridge-chain-client-evm-bsc-9006
    spec:
      containers:
        - name: obridge-chain-client-evm-bsc-9006
          image: otmoic/otmoic-chainclient-evm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9100
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "obridge-chain-client-status-report-bsc"
            - name: CHAIN_TYPE
              value: "evm"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SYSTEM_CHAIN_ID
              value: "9006"
            - name: CHAIN_ID
              value: "97"
            - name: OS_API_KEY
              value: {{ .Values.os.appKey }}
            - name: OS_API_SECRET
              value: {{ .Values.os.appSecret }}
            - name: OS_SYSTEM_SERVER
              value: system-server.user-system-{{ .Values.bfl.username }}
            - name: CONTRACT_ADDRESS
              value: "0xE09795702F95ff8Df93f41043f31C8A3b1789b8B"
            - name: START_BLOCK
              value: "0"
            - name: RPC_URL
              value: "https://bsc-testnet.blockpi.network/v1/rpc/public"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: 'false'
