apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-evm-polygon-server-966
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: obridge-chain-client-evm-polygon-966
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-evm-polygon-api-966
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-evm-polygon-966
  namespace: {{ .Release.Namespace }}
  labels:
    app: obridge-chain-client-evm-polygon-966
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-evm-polygon-966
  template:
    metadata:
      labels:
        app: obridge-chain-client-evm-polygon-966
    spec:
      containers:
        - name: obridge-chain-client-evm-polygon-966
          image: kldtks/edge:otmoic-chainclient-evm-latest
          ports:
            - containerPort: 9100
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "obridge-chain-client-status-report-polygon"
            - name: CHAIN_TYPE
              value: "evm"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SYSTEM_CHAIN_ID
              value: "966"
            - name: CHAIN_ID
              value: "80001"
            - name: OS_API_KEY
              value: {{ .Values.os.appKey }}
            - name: OS_API_SECRET
              value: {{ .Values.os.appSecret }}
            - name: OS_SYSTEM_SERVER
              value: system-server.user-system-{{ .Values.bfl.username }}
            - name: CONTRACT_ADDRESS
              value: "0xd116c529E3188be0C1E6B53Ee499229e29B1E6fA"
            - name: START_BLOCK
              value: "0"
            - name: RPC_URL
              value: "https://polygon-testnet.public.blastapi.io"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: 'false'
