---
apiVersion: v1
data:
  nginx.conf: |
    server {

      listen 8080;
      access_log /opt/bitnami/openresty/nginx/logs/access.log;
      error_log /opt/bitnami/openresty/nginx/logs/error.log;

      proxy_connect_timeout                          30s;
      proxy_send_timeout                             60s;
      proxy_read_timeout                             300s;
      proxy_set_header      host                      $host;
      proxy_set_header      x-forwarded-host          $http_host;

      proxy_http_version 1.1;

      proxy_set_header upgrade $http_upgrade;
      proxy_set_header connection "upgrade";

      location / {
        {{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
        proxy_pass http://vllm:8000;
        {{- else }}
        proxy_pass http://{{ .Release.Name }}.{{ .Release.Name }}-{{ .Values.admin }}:8000;
        {{- end }}
      }
    }

kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vllmclient
  {{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
  name: vllmclient
  {{- else }}
  name: vllm
  {{- end }}
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vllmclient
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: vllmclient
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 438
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: nginx
          image: docker.io/aboveos/bitnami-openresty:1.25.3-2
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OPENRESTY_CONF_FILE
              value: /etc/nginx/nginx.conf
          startupProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 40
            failureThreshold: 120
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks/nginx.conf
              subPath: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: vllmclient
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: vllmclient
  ports:
    - name: vllmclient
      protocol: TCP
      port: 8080
      targetPort: 8080
