apiVersion: v1
kind: Service
metadata:
  name: kaneo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kaneo
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kaneo
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: 5173
    targetPort: http
    protocol: TCP
