---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nostream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostream
  template:
    metadata:
      labels:
        app: nostream
    spec:
      initContainers:
      - name: init-nostream-data
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          mkdir -p /app/.nostr && \
          touch /app/.nostr/settings.yaml && \
          chown -R 1000:1000 /app/.nostr
        volumeMounts:
        - name: nostream-config
          mountPath: /app/.nostr
      containers:
      - name: nostream
        image: "beclab/nostream:v0.0.1"
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        env:
        - name: RELAY_PORT
          value: "8008"
        - name: NOSTR_CONFIG_DIR
          value: "/app/.nostr"
        - name: DB_USER
          value: "{{ .Values.postgres.username }}"  
        - name: DB_PASSWORD
          value: "{{ .Values.postgres.password }}"  
        - name: DB_NAME
          value: "{{ .Values.postgres.databases.nostream }}" 
        - name: DB_HOST
          value: {{ .Values.postgres.host }}
        - name: DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: REDIS_USER
          value: ""
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}
        ports:
        - containerPort: 8008
        volumeMounts:
        - name: nostream-config
          mountPath: /app/.nostr
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: nostream-config
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
