apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: rank-train-task-en-10800
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '30/30 * * * *'
  startingDeadlineSeconds: 0
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterCompletion: 3600
    secondsAfterFailure: 3600
  workflowSpec:
    entrypoint: trainFlow
    volumes:
      - name: model
        hostPath:
          type: DirectoryOrCreate
          path: >-
            {{ .Values.userspace.appdata }}/rss/model/en
    templates:
      - name: trainFlow
        steps:
          - - name: rank-train
              template: rank-train-template
      - name: rank-train-template
        container:
          image: aboveos/bertv2train
          imagePullPolicy: Always
          env:
            - name: KNOWLEDGE_BASE_API_URL
              value: {{ .Values.apiUrl }}
            - name: TERMINUS_RECOMMEND_SOURCE_NAME
              value: bytetrade-bert_v2_en_10800
          volumeMounts:
            - mountPath: /opt/rank_model
              name: model
