apiVersion: v1
kind: Service
metadata:
  name: genoffice
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: genoffice
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    io.kompose.service: genoffice
