apiVersion: v1
kind: ServiceAccount
metadata:
  name: dendrite-signing-key
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/component: signingkey-job
    helm.sh/chart: dendrite-0.13.5
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/instance: dendrite
    app.kubernetes.io/version: "0.13.4"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dendrite-signing-key
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/component: signingkey-job
    helm.sh/chart: dendrite-0.13.5
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/instance: dendrite
    app.kubernetes.io/version: "0.13.4"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - dendrite-signing-key
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dendrite-signing-key
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/component: signingkey-job
    helm.sh/chart: dendrite-0.13.5
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/instance: dendrite
    app.kubernetes.io/version: "0.13.4"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dendrite-signing-key
subjects:
  - kind: ServiceAccount
    name: dendrite-signing-key
    namespace: '{{ .Release.Namespace }}'