{{- $dendriteDomainENV := split  ","  .Values.domain.dendrite -}}
{{- $dendriteDomain := index $dendriteDomainENV "_0" -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: dendrite-signing-key
  namespace: '{{ .Release.Namespace }}'
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: dendrite-conf
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  dendrite.yaml: |
    
    app_service_api:
      config_files: []
      disable_tls_validation: false
    client_api:
      enable_registration_captcha: true
      guests_disabled: true
      rate_limiting:
        cooloff_ms: 500
        enabled: true
        exempt_user_ids: null
        threshold: 20
      recaptcha_bypass_secret: ""
      recaptcha_private_key: "6LcPcwwqAAAAAIT5RUP9-6RqRV_fA8SvYPrjldhk"
      recaptcha_public_key: "6LcPcwwqAAAAAL8n9EDCqpCDOQ5KEUmxGbaMrDaW"
      recaptcha_siteverify_api: "https://www.google.com/recaptcha/api/siteverify"
      registration_disabled: false
      registration_shared_secret: "7cfc30051a2893124ffdc3b55fc01f67bc5a373491793f76f6d3b6b04896d95c"
      turn:
        turn_password: ""
        turn_shared_secret: ""
        turn_uris: []
        turn_user_lifetime: 24h
        turn_username: ""
    federation_api:
      disable_http_keepalives: false
      disable_tls_validation: false
      key_perspectives:
      - keys:
        - key_id: ed25519:auto
          public_key: Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw
        - key_id: ed25519:a_RXGa
          public_key: l8Hft5qXKn1vfHrg3p4+W8gELQVo8N13JkluMfmn2sQ
        server_name: "{{ $dendriteDomain }}"
      prefer_direct_fetch: false
      send_max_retries: 16
    global:
      cache:
        max_age: 1h
        max_size_estimated: 1gb
      database:
        conn_max_lifetime: -1
        connection_string: postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.dendrite }}
        max_idle_conns: 5
        max_open_conns: 90
      disable_federation: false
      dns_cache:
        cache_lifetime: 10m
        cache_size: 256
        enabled: false
      jetstream:
        addresses: []
        disable_tls_validation: true
        in_memory: false
        storage_path: /data/jetstream
        topic_prefix: Dendrite
      key_validity_period: 168h0m0s
      metrics:
        basic_auth:
          password: metrics
          user: metrics
        enabled: false
      old_private_keys: null
      presence:
        enable_inbound: false
        enable_outbound: false
      private_key: /etc/dendrite/secrets/signing.key
      profiling:
        enabled: false
        port: 65432
      report_stats:
        enabled: false
        endpoint: https://matrix.org/report-usage-stats/push
      server_name: "{{ $dendriteDomain }}"
      server_notices:
        avatar_url: ""
        display_name: Server Alerts
        enabled: false
        local_part: _server
        room_name: Server Alerts
      trusted_third_party_id_servers:
      - matrix.org
      - vector.im
      well_known_client_name: "DendriteInTerminus"
      well_known_server_name: "{{ $dendriteDomain }}"
    logging:
    - level: info
      type: std
    media_api:
      base_path: /data/media_store
      dynamic_thumbnails: false
      max_file_size_bytes: 10485760
      max_thumbnail_generators: 10
      thumbnail_sizes:
      - height: 32
        method: crop
        width: 32
      - height: 96
        method: crop
        width: 96
      - height: 480
        method: scale
        width: 640
    mscs:
      mscs: []
    sync_api:
      real_ip_header: X-Real-IP
      search:
        enabled: true
        index_path: /data/search
        language: en
    user_api:
      auto_join_rooms: []
      bcrypt_cost: 10
      openid_token_lifetime_ms: 3600000
      push_gateway_disable_tls_validation: false
    version: 2