apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: dendrite
  labels:
    helm.sh/chart: dendrite-0.13.5
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/instance: dendrite
    app.kubernetes.io/version: "0.13.4"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/instance: dendrite
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 8008