kind: Deployment
apiVersion: apps/v1
metadata:
  name: cinny
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: cinny
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinny
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cinny
    spec:
      containers:
        - name: cinny
          image: 'ajbura/cinny:v3.2.0'
          ports:
            - name: http-0
              containerPort: 80
              protocol: TCP
          resources: 
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 20Mi
              cpu: 1m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: cinny
  labels:
    app: cinny
spec:
  selector:
    app: cinny
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80