---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: documenso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: documenso
    spec:
      containers:
        - name: documenso
          image: "docker.io/beclab/documenso-documenso:v2.6.0"
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DISPLAY
              value: ":0"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: documenso
                  key: NEXTAUTH_SECRET
            - name: NEXT_PRIVATE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: documenso
                  key: NEXT_PRIVATE_ENCRYPTION_KEY
            - name: NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY
              valueFrom:
                secretKeyRef:
                  name: documenso
                  key: NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY
            - name: NEXT_PRIVATE_SMTP_FROM_ADDRESS
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_FROM_ADDRESS }}'
            - name: NEXT_PRIVATE_SMTP_FROM_NAME
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_FROM_NAME | default "Documenso" }}'
            - name: NEXT_PRIVATE_SMTP_HOST
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_HOST }}'
            - name: NEXT_PRIVATE_SMTP_PASSWORD
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_PASSWORD }}'
            - name: NEXT_PRIVATE_SMTP_PORT
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_PORT }}'
            - name: NEXT_PRIVATE_SMTP_SECURE
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_SECURE | default "false" }}'
            - name: NEXT_PRIVATE_SMTP_USERNAME
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_USERNAME }}'
            - name: NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS | default "false" }}'
            - name: NEXT_PRIVATE_SMTP_TRANSPORT
              value: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_TRANSPORT | default "smtp-auth" }}'
          envFrom:
            - configMapRef:
                name: documenso-config
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/documenso/cert.p12
              name: documenso-cert
      volumes:
        - name: documenso-cert
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/cert.p12"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/documenso/cert.p12"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/documenso/cert.p12"
            {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: documenso
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: documenso
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: documenso
