---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docmost-config
  namespace: {{ .Release.Namespace }}
data:
  JWT_TOKEN_EXPIRES_IN: "30d"
  PORT: "3000"
  STORAGE_DRIVER: "local"
  FILE_UPLOAD_SIZE_LIMIT: "100mb"

  # smtp config
  MAIL_DRIVER: "smtp"
  SMTP_HOST: "{{ .Values.olaresEnv.SMTP_HOST }}"
  SMTP_PORT: "{{ .Values.olaresEnv.SMTP_PORT }}"
  SMTP_USERNAME: "{{ .Values.olaresEnv.SMTP_USERNAME }}"
  SMTP_PASSWORD: "{{ .Values.olaresEnv.SMTP_PASSWORD }}"
  SMTP_SECURE: "{{ .Values.olaresEnv.SMTP_SECURE }}"
  MAIL_FROM_ADDRESS: "{{ .Values.olaresEnv.SMTP_FROM_ADDRESS }}"
  MAIL_FROM_NAME: "{{ .Values.olaresEnv.SMTP_FROM_NAME }}"
