{{- $webDomain := printf "%s.%s" "denostr" .Values.user.zone -}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: denostr-svc
  labels:
    component: denostr
spec:
  ports:
    - name: ws
      port: 8008
      targetPort: 8008
  selector:
    component: denostr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: denostr
  labels:
    component: denostr
spec:
  serviceName: denostr-svc
  replicas: 3
  selector:
    matchLabels:
      component: denostr
  template:
    metadata:
      labels:
        component: denostr
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: relay
          image: ghcr.io/guakamoli/denostr:v0.1.1-worker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: denostr-mongodb
                  key: mongodb-root-password
            - name: MONGO_URI
              value: "mongodb://root:$(MONGODB_ROOT_PASSWORD)@denostr-mongodb-0.denostr-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:27017/db?replicaSet=rs0&authSource=admin"
              # value: "mongodb://root:$(MONGODB_ROOT_PASSWORD)@denostr-db-mongodb:27017/db?replicaSet=rs0&authSource=admin"
          ports:
            - containerPort: 8008
              name: ws
          volumeMounts:
            - mountPath: /app/.nostr
              name: denostr-worker-config-val
      volumes:
        - name: denostr-worker-config-val
          configMap:
            name: denostr-worker-config
            items:
            - key: settings.yaml
              path: settings.yaml

---
apiVersion: v1
data:
  settings.yaml: |
    info:
      relay_url: ws://{{ $webDomain }}
      name: "nostr relay by denostr"
      description: Deno-based, cloud-native nostr implementation supported by ByteTrade and Revo, forked from nostream.
      pubkey: replace-with-your-pubkey-in-hex
      contact: operator@{{ $webDomain }}
    payments:
      enabled: false
      processor: zebedee
      feeSchedules:
        admission:
        - enabled: false
          description: Admission fee charged per public key in msats (1000 msats = 1 satoshi)
          amount: 1000000
          whitelists:
            pubkeys:
              - replace-with-your-pubkey-in-hex
              # Allow the following Zap providers:
              # LightningTipBot by Calle
              - "fcd720c38d9ee337188f47aac845dcd8f590ccdb4a928b76dde18187b4c9d37d"
    paymentsProcessors:
      zebedee:
        baseURL: https://api.zebedee.io/
        callbackBaseURL: https://denostr.{{ $webDomain }}/callbacks/zebedee
        ipWhitelist:
          - "3.225.112.64"
          - "::ffff:3.225.112.64"
      lnbits:
        baseURL: https://lnbits.{{ $webDomain }}/
        callbackBaseURL: https://denostr.{{ $webDomain }}/callbacks/lnbits
    network:
      maxPayloadSize: 524288
      # Comment the next line if using CloudFlare proxy
      remoteIpHeader: x-forwarded-for
      # Uncomment the next line if using CloudFlare proxy
      # remoteIpHeader: cf-connecting-ip
    workers:
      count: 0
    mirroring:
      static: []
    limits:
      invoice:
        rateLimits:
        - period: 60000
          rate: 12
        - period: 3600000
          rate: 30
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
      connection:
        rateLimits:
        - period: 1000
          rate: 24
        - period: 60000
          rate: 72
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
      event:
        eventId:
          minLeadingZeroBits: 0
        kind:
          whitelist: []
          blacklist: []
        pubkey:
          minBalance: 0
          minLeadingZeroBits: 0
          whitelist: []
          blacklist: []
        createdAt:
          maxPositiveDelta: 900
          maxNegativeDelta: 0
        content:
        - description: 64 KB for event kind ranges 0-10 and 40-49
          kinds:
          - - 0
            - 10
          - - 40
            - 49
          maxLength: 65536
        - description: 96 KB for event kind ranges 11-39 and 50-max
          kinds:
          - - 11
            - 39
          - - 50
            - 9007199254740991
          maxLength: 98304
        rateLimits:
        - description: 30 events/min for event kinds 0, 3, 40 and 41
          kinds:
          - 0
          - 3
          - 40
          - 41
          period: 60000
          rate: 30
        - description: 144 events/min for event kinds 1, 2, 4 and 42
          kinds:
          - 1
          - 2
          - 4
          - 42
          period: 60000
          rate: 144
        - description: 1200 events/min for encrypted channel event kinds 104 and 140-142
          kinds:
          - 104
          - 140
          - 141
          - 142
          period: 60000
          rate: 1200
        - description: 60 events/min for event kind ranges 5-7 and 43-49
          kinds:
          - - 5
            - 7
          - - 43
            - 49
          period: 60000
          rate: 60
        - description: 24 events/min for replaceable events and parameterized replaceable
            events
          kinds:
          - - 10000
            - 19999
          - - 30000
            - 39999
          period: 60000
          rate: 24
        - description: 120 events/min for ephemeral events
          kinds:
          - - 20000
            - 29999
          period: 60000
          rate: 120
        - description: 4800 events/hour for all events
          period: 3600000
          rate: 4800
        whitelists:
          pubkeys: []
          ipAddresses:
          - "::1"
          - "10.10.10.1"
          - "::ffff:10.10.10.1"
      client:
        subscription:
          maxSubscriptions: 20
          maxFilters: 10
      message:
        rateLimits:
        - description: 720 raw messages/min
          period: 60000
          rate: 720
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
kind: ConfigMap
metadata:
  labels:
    component: denostr
  name: denostr-worker-config
  namespace: {{ .Release.Namespace }}