image: docker.io/beclab/music:0.1.32
imagePullPolicy: IfNotPresent

postgres:
  host: postgres
  port: 5432
  username: music
  password: ""
  databases:
    music: music

userspace:
  appData: /tmp/music

workloads:
  music:
    replicaCount: 1
