{{- $planeDomainENV := split "," .Values.domain.plane }}
{{- $planeDomain := index $planeDomainENV "_0" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Namespace }}
data:
  DEBUG: "0"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3100,https://{{ $planeDomain }}"

  # Database Settings
  POSTGRES_USER: "{{ .Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_DB: "{{ .Values.postgres.databases.plane }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.plane }}"

  # Redis Settings
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_URL: "redis://:{{ .Values.redis.password }}@{{ .Values.redis.host }}:{{ .Values.redis.port}}/"

  # RabbitMQ Settings
  RABBITMQ_HOST: "{{ .Values.rabbitmq.host }}"
  RABBITMQ_PORT: "{{ .Values.rabbitmq.port }}"
  RABBITMQ_USER: "{{ .Values.rabbitmq.username }}"
  RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.password }}"
  RABBITMQ_VHOST: "{{ .Values.rabbitmq.vhosts.plane}}"

  # AWS Settings
  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: "{{ .Values.minio.username }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.minio.password }}"
  AWS_S3_ENDPOINT_URL: "http://{{ .Values.minio.host}}:{{ .Values.minio.port }}"
  AWS_S3_BUCKET_NAME: "{{ .Values.minio.buckets.plane }}"
  FILE_SIZE_LIMIT: "5242880"

  # Docker Settings
  DOCKERIZED: "1"
  USE_MINIO: "0"

  # Web and domain settings
  WEB_URL: "https://{{ $planeDomain }}"

  # Gunicorn Workers
  GUNICORN_WORKERS: "2"

  # Base URLs
  ADMIN_BASE_URL: "https://{{ $planeDomain }}"
  ADMIN_BASE_PATH: "/god-mode"

  SPACE_BASE_URL: "https://{{ $planeDomain }}"
  SPACE_BASE_PATH: "/spaces"

  APP_BASE_URL: "https://{{ $planeDomain }}"
  APP_BASE_PATH: ""

  LIVE_BASE_URL: "https://{{ $planeDomain }}"
  LIVE_BASE_PATH: "/live"

  LIVE_SERVER_SECRET_KEY: "secret-key"

  # Other settings
  HARD_DELETE_AFTER_DAYS: "60"
  MINIO_ENDPOINT_SSL: "0"
  API_KEY_RATE_LIMIT: "60/minute"
  SECRET_KEY: "s3cRet$jf8!9Xvn2%Pa29#KwR7$e"
