apiVersion: v1
kind: ConfigMap
metadata:
  name: appstore-adminv2-config
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: source
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  AUTH_MODE: olares_header
  LLDAP_READONLY_URL: http://lldap-provider-svc.os-framework:28080
  LLDAP_RESYNC_SECONDS: "30"
