apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: source
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECERT: "7149201245"
  INTERNAL_API_TOKEN: 4765f2f41c4f28599b6e049f1078e74288f8b54e287f1e5ab25db48b5e063df5
