source_url: https://huggingface.co/TheBloke/openchat-3.5-1210-GGUF/resolve/main/openchat-3.5-1210.Q4_K_M.gguf
id: openchat7b
object: model
name: Openchat-3.5 7B Q4
version: '1.0'
description: The performance of this open-source model surpasses that of ChatGPT-3.5 and Grok-1 across various benchmarks.
format: gguf
settings:
  ctx_len: 4096
  prompt_template: |-
    GPT4 Correct User: {prompt}<|end_of_turn|>GPT4 Correct Assistant:
parameters:
  temperature: 0.7
  top_p: 0.95
  stream: true
  max_tokens: 4096
  stop: 
  - "<|end_of_turn|>"
  frequency_penalty: 0
  presence_penalty: 0
metadata:
  author: Openchat
  tags:
  - 7B
  - Finetuned
  size: 4370000000
engine: nitro
