{{- $gpuInfo := include "GPU.getGPUInfo" . | fromJson -}}
{{- $is50Series := $gpuInfo.is50Series -}}
{{- $paddleocrImage := "" -}}
{{- $enableASR := false -}}
{{- if eq $is50Series "true" -}}
  {{- $paddleocrImage = "docker.io/bleachzou/paddleocr3.4-nividia-gpu-sm120-offline:0.0.1" -}}
{{- else -}}
  {{- $paddleocrImage = "docker.io/bleachzou/paddleocr3.4-nividia-gpu-offline:0.0.1" -}}

{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paddleocr
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: paddleocr
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: paddleocr
  template:
    metadata:
      labels:
        io.kompose.service: paddleocr
    spec:
      containers:
        - name: paddleocr
          image: {{ $paddleocrImage }}
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,graphics,utility,video,display"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: "2000m"
              memory: 9Gi
          volumeMounts:
            - name: voice-data
              mountPath: /code/data
            - name: logfile
              mountPath: /logfile
