apiVersion: apps/v1
kind: Deployment
metadata:
  name: denny
  namespace: {{ .Release.Namespace }}
  labels:
    app: denny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: denny
  template:
    metadata:
      labels:
        app: denny
    spec:
      containers:
      - name: denny
        image: ghcr.io/guakamoli/denny:latest
        resources:
          requests:
            cpu: 250m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 64Mi
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: denny-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: denny
  ports:
    - protocol: TCP
      port: 80

