apiVersion: v2
appVersion: 1.0.1
description: Wise (shared) — frontend + knowledge backend (knowledge-base-api + vectorcrawl + camoufox + nginx + wise frontend)
name: knowledgev3
type: application
version: 1.2.14