---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000" 
        - name: PUID
          value: "1000" 
        - name: UMASK
          value: "002" 
        - name: TZ
          value: Etc/UTC
        name: bazarr
        image: cr.hotio.dev/hotio/bazarr
        ports:
        - containerPort: 6767
        volumeMounts:
        - mountPath: /config
          name: bazarr-config
      volumes:
      - name: bazarr-config
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appdata }}/bazarr 
        

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
