apiVersion: v2
name: voice
description: Voice production on Olares audio models
icon: https://raw.githubusercontent.com/beclab/voice/main/deploy/voice/assets/icon.png
type: application
version: 0.4.5
appVersion: "0.4.5"
