image: docker.io/beclab/voice:0.4.5
imagePullPolicy: IfNotPresent

postgres:
  host: postgres
  port: 5432
  username: voice
  password: ""
  databases:
    voice: voice

userspace:
  appData: /tmp/voice

workloads:
  voice:
    replicaCount: 1
