{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vllmqwen330ba3binstruct4bit
  namespace: "{{ .Release.Namespace }}"
  labels:
    io.kompose.service: vllmqwen330ba3binstruct4bit
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vllmqwen330ba3binstruct4bit
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: vllmqwen330ba3binstruct4bit
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.11.0
          args:
            - "--model"
            - "cpatonn/Qwen3-30B-A3B-Instruct-2507-AWQ-4bit"
            - '--max-model-len'
            - '8000'
            - '--tensor-parallel-size'
            - '1'
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HF_TOKEN
              value: "{{ .Values.olaresEnv.OLARES_USER_HUGGINGFACE_TOKEN }}"
            - name: VLLM_PORT
              value: "8000"
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 40
            failureThreshold: 120
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          resources:
            limits:
              cpu: "20"
              memory: 19Gi
            requests:
              cpu: 500m
              memory: 4Gi
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: data
      volumes:
        - name: data
          hostPath:
            path: "{{ .Values.sharedlib }}/ai/vllm/qwen330ba3binstruct4bit"
            type: DirectoryOrCreate
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vllm
  namespace: "{{ .Release.Namespace }}"
  labels:
    io.kompose.service: vllm
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: vllmqwen330ba3binstruct4bit
status:
  loadBalancer: {}
{{- end }}
