{{- $mastodonDomainENV := split  ","  .Values.domain.mastodonapache -}}
{{- $webDomain := index $mastodonDomainENV "_0" -}}

{{- $localDomain := $webDomain -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mastodon-default
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: mastodon
    helm.sh/chart: mastodon-0.1.2
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: mastodon
data:
  OIDC_CLIENT_ID: "{{ .Values.oidc.client.id }}"
  OIDC_CLIENT_SECRET: "{{ .Values.oidc.client.secret }}"
  OIDC_DISCOVERY: 'true'
  OIDC_DISPLAY_NAME: "Authelia"
  OIDC_ENABLED: 'true'
  OIDC_ISSUER: "{{ .Values.oidc.issuer }}"
  OIDC_SCOPE: 'openid,profile,email'
  OIDC_SECURITY_ASSUME_EMAIL_IS_VERIFIED: 'true'
  OIDC_UID_FIELD: "preferred_username"
  MASTODON_ADMIN_USERNAME: "{{ .Values.adminUser }}"
  MASTODON_ADMIN_EMAIL: "{{ .Values.adminEmail }}"
  RAILS_ENV: "production"
  NODE_ENV: "production"
  DB_HOST: "{{ .Values.postgres.host }}"
  MASTODON_DATABASE_HOST: "{{ .Values.postgres.host }}"
  DB_PORT: "{{ .Values.postgres.port }}"
  MASTODON_DATABASE_PORT_NUMBER: "{{ .Values.postgres.port }}"
  DB_NAME: "{{ .Values.postgres.databases.mastodon }}"
  MASTODON_DATABASE_NAME: "{{ .Values.postgres.databases.mastodon }}"
  DB_USER: "{{ .Values.postgres.username }}"
  MASTODON_DATABASE_USERNAME: "{{ .Values.postgres.username }}"
  ES_ENABLED: "true"
  ES_HOST: "mastodon-elasticsearch"
  MASTODON_ELASTICSEARCH_HOST: "elasticsearch"
  ES_PORT: "9200"
  MASTODON_ELASTICSEARCH_PORT_NUMBER: "9200"
  WEB_DOMAIN: "{{ $webDomain }}"
  LOCAL_DOMAIN: "{{ $localDomain }}"
  LOCAL_HTTPS: "true"
  AUTHORIZED_FETCH: "false"
  STREAMING_API_BASE_URL: "wss://{{ $webDomain }}"
  REDIS_HOST: "mastodon-redis-master"
  REDIS_PORT: "6379"
  S3_ENABLED: "true"
  S3_BUCKET: "{{ .Values.minio.buckets.mastodon }}"
  S3_ENDPOINT: "http://{{ .Values.minio.host }}"
  S3_HOSTNAME: "{{ .Values.minio.host }}"
  S3_REGION: "us-east-1"
  S3_ALIAS_HOST: "{{ $webDomain }}/s3storage"
  S3_PROTOCOL: "http"
  SMTP_SERVER: "{{ .Values.olaresEnv.SMTP_SERVER }}"
  SMTP_PORT: "{{ .Values.olaresEnv.SMTP_PORT }}"
  SMTP_LOGIN: "{{ .Values.olaresEnv.SMTP_LOGIN }}"
  SMTP_PASSWORD: "{{ .Values.olaresEnv.SMTP_PASSWORD }}"
  SMTP_FROM_ADDRESS: "{{ .Values.olaresEnv.SMTP_FROM_ADDRESS }}"
  SMTP_DOMAIN: "{{ .Values.olaresEnv.SMTP_DOMAIN }}"
  SMTP_DELIVERY_METHOD: "{{ .Values.olaresEnv.SMTP_DELIVERY_METHOD }}"
  SMTP_AUTH_METHOD: "{{ .Values.olaresEnv.SMTP_AUTH_METHOD }}"
  SMTP_CA_FILE: "{{ .Values.olaresEnv.SMTP_CA_FILE }}"
  SMTP_OPENSSL_VERIFY_MODE: "{{ .Values.olaresEnv.SMTP_OPENSSL_VERIFY_MODE }}"
  SMTP_ENABLE_STARTTLS_AUTO: "{{ .Values.olaresEnv.SMTP_ENABLE_STARTTLS_AUTO }}"
  SMTP_ENABLE_STARTTLS: "{{ .Values.olaresEnv.SMTP_ENABLE_STARTTLS }}"
  SMTP_TLS: "{{ .Values.olaresEnv.SMTP_TLS }}"
  SMTP_SSL: "{{ .Values.olaresEnv.SMTP_SSL }}"
  