---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: firefox-claim0
#   name: firefox-claim0
#   namespace: {{ .Release.Namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# status: {}
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: testpermission
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: testpermission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: testpermission
    spec:
      containers:
        - env:
            - name: CHROME_CLI
              value: https://www.linuxserver.io/
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DISPLAY
              value: ':0'               
            - name: TEST_VERSION
              value: '{{ .Values.olaresEnv.TEST_VERSION }}'
            - name: TEST_PHONE
              value: '{{ .Values.olaresEnv.TEST_PHONE }}'
            - name: TEST_ROOT_PATH
              value: '{{ .Values.olaresEnv.TEST_ROOT_PATH }}'
          image: docker.io/aboveos/linuxserver-firefox:131.0.3
          name: testpermission
          command:
            - bash
            - '-c'
            - >-
              apt-get update; apt-get install -y fonts-wqy-zenhei
              fonts-wqy-microhei; fc-cache -fv; /init
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 3000m
              memory: 3Gi
          ports:
            - containerPort: 3000
            - containerPort: 3001
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /home
              name: userdata
            - name: dshm 
              mountPath: /dev/shm     
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: {{ .Values.userspace.appCache }}
              {{- else }}
            path: {{ .Values.userspace.appCache }}
              {{- end }}
            {{- else }}
            path: {{ .Values.userspace.appCache }}
            {{- end }}
        - hostPath:
            path: '{{ .Values.userspace.userData }}'
            type: DirectoryOrCreate
          name: userdata
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi 
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: testpermission
  name: testpermission
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: testpermission
status:
  loadBalancer: {}
