


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-provider
  namespace: {{ .Release.Namespace }}
  labels:
    app: twitter-provider
    applications.app.bytetrade.io/author: bytetrade.io
    provider: 'true'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: twitter-provider
  template:
    metadata:
      labels:
        app: twitter-provider
    spec:
      containers:
        - name: provider-proxy
          image: beclab/provider-proxy:0.1.0
          imagePullPolicy: IfNotPresent
          args:
          - --logtostderr
          - --insecure-listen-address=:28080
          - --upstream=http://twitter-svc:3060/
          ports:
          - containerPort: 28080
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: "500m"
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-provider
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: twitter-provider
  ports:
    - name: server
      protocol: TCP
      port: 28080
      targetPort: 28080
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:{{ .Release.Namespace }}:twitter-provider
  annotations:
    provider-registry-ref: '{{ .Release.Namespace }}/twitter-provider'
    provider-service-ref: 'twitter-provider.{{ .Release.Namespace }}:28080'
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:sa:default:twitter
rules:
  - apiGroups:
      - '*'
    resources:
      - clusterrolebindings
      - clusterroles
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - tokenreviews
      - subjectaccessreviews
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend:sa:default:twitter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend:sa:default:twitter
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}