
---
apiVersion: v1
data:
  local.ini: |
    [admins]
    admin = -pbkdf2-97e50faaa81dfda26c7ef6178808ae441f87092f,8dba11bb4382e2d3fb9799ab60a1212a,10

    [couchdb]
    single_node=true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    max_http_request_size = 4294967296

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    max_age = 3600
kind: ConfigMap
metadata:
  name: obsidian-config
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      containers:
      - name: server
        image: couchdb:3.1.2
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: server-data
        - mountPath: /opt/couchdb/etc/local.ini
          name: obsidian-config
          subPath: local.ini  
        command:
        - tini
        - --
        - /opt/couchdb/bin/couchdb
        # env:
        # - name: COUCHDB_USER
        #   value: admin 
        # - name: COUCHDB_PASSWORD
        #   value: password 
        
      volumes:
      - name: server-data
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appCache }}/obsidian 
      - name: obsidian-config
        configMap:
          defaultMode: 420
          name: obsidian-config
          items:
          - key: local.ini
            path: local.ini        

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
