image:
  repository: docker.io/olareshzy/audio-speakrs
  tag: a2bb141
  pullPolicy: IfNotPresent

llminit:
  repository: docker.io/beclab/llm-init
  tag: v1.5.2
  pullPolicy: IfNotPresent

model:
  source: hf://avencera/speakrs-models --exclude *.mlmodelc/*
  engineArgs: "--execution-mode cuda-fast"

hf:
  endpoint: https://huggingface.co/

logLevel: info

workloads:
  audiospeakrsdiarfastv3:
    replicaCount: 1
  llminit:
    replicaCount: 1

userspace:
  appData: /tmp/audiospeakrsdiarfastv3-appdata
  appCache: /tmp/audiospeakrsdiarfastv3-appcache
  appCommon: /tmp/audiospeakrsdiarfastv3-appcommon
