apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  NOTE_GATEWAY_API_KEY: {{ index (.Values.olaresEnv | default dict) "GATEWAY_API_KEY" | default "" | quote }}
  NOTE_DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.note }}?sslmode=disable"
