kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: home
          hostPath:
            type: Directory
            path: {{ .Values.userspace.userData }}
      initContainers:
        - name: init-chmod-data
          image: 'busybox:latest'
          command:
            - sh
            - '-c'
            - |
              chown -R 1000:1000 /home
          resources: {}
          volumeMounts:
            - name: home
              mountPath: /home
          securityContext:
            runAsUser: 0
      containers:
        - name: qbittorrent
          image: 'kldtks/edge:qbittorrent-v0.1'
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PGID
              value: "1000" 
            - name: PUID
              value: "1000" 
            - name: UMASK
              value: "002" 
            - name: TZ
              value: UTC
          volumeMounts:
            - name: home
              mountPath: /home
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      automountServiceAccountToken: true
      securityContext: {}
      enableServiceLinks: true
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600

---
apiVersion: sys.bytetrade.io/v1alpha1
kind: ProviderRegistry
metadata:
  name: {{ .Release.Name }}-svc
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  dataType: legacy_api
  deployment: qbittorrent
  description: qbittorrent legacy api
  endpoint: {{ .Release.Name }}-svc.{{ .Release.Namespace }}:8080
  group: api.qbittorrent
  kind: provider
  namespace: {{ .Release.Namespace }}
  version: v1
status:
  state: active