apiVersion: v2
appVersion: v1.16.7
description: Instant Distributed Tracing
icon: https://d2q89wckrml3k4.cloudfront.net/logo.png
kubeVersion: '>= 1.19.0-0'
name: odigos
type: application
version: 1.0.1
