image: docker.io/luolong01/dina:0.18.0
imagePullPolicy: IfNotPresent

workloads:
  dina:
    replicaCount: 1

dev:
  hotReload: false
  sourceSubPath: devsrc

olaresEnv:
  LLM_GATEWAY_URL: http://router-svc.router-shared/v1
  OLARES_APP_ID: dina
  DINA_ROUTER_API_KEY: ""
  DINA_DEFAULT_MODEL: ""
