# Source: obridge-chain-client-evm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-evm-bsc-server-9006
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: obridge-chain-client-evm-bsc-9006
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-evm-bsc-api-9006
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-evm-bsc-9006
  namespace: {{ .Release.Namespace }}
  labels:
    app: obridge-chain-client-evm-bsc-9006
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-evm-bsc-9006
  template:
    metadata:
      labels:
        app: obridge-chain-client-evm-bsc-9006
    spec:
      containers:
      - name: obridge-chain-client-evm-bsc-9006
        image: kldtks/edge:otmoic-chainclient-evm-latest
        ports:
          - containerPort: 9100
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: EVM_CLIENT_PORT
            value: "9100"
          - name: REDIS_HOST
            value: "obridge-relay-db-redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: RPC_URL
            value: "https://public.stackup.sh/api/v1/node/bsc-testnet"
          - name: CONTRACT_ADDRESS
            value: "0xE09795702F95ff8Df93f41043f31C8A3b1789b8B"
          - name: SYSTEM_CHAIN_ID
            value: "9006"
          - name: CHAIN_ID
            value: "97"
          - name: START_BLOCK
            value: "0"
          - name: SERVER_URL_TRANSFER_OUT
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_out"
          - name: SERVER_URL_TRANSFER_IN
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_in"
          - name: SERVER_URL_CONFIRM
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_confirm"
          - name: SERVER_URL_REFUNDED
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_refunded"
          - name: AUTO_START
            value: 'true'
          - name: RELAY_WALLET_ADDRESS
            value: '0x10FE2771907B0c4245695daD7e9Ed064d45860f8'
          - name: RELAY_WALLET_PRIVATE_KEY
            value: 058d185b433e50118a1bd451c13a7602df50b060e4a83e3b5057f5feff98fd3f
          - name: RELAY_WALLET
            value: 'true'
          - name: START_TOP_HEIGHT
            value: 'true'