# Source: obridge-chain-client-xrp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-xrp-server-144
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: obridge-chain-client-xrp-144
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-xrp-api-144
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-xrp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-xrp-144
  namespace: {{ .Release.Namespace }}
  labels:
    app: obridge-chain-client-xrp-144
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-xrp-144
  template:
    metadata:
      labels:
        app: obridge-chain-client-xrp-144
    spec:
      containers:
      - name: obridge-chain-client-xrp-144
        image: kldtks/edge:otmoic-chainclient-xrp-latest
        ports:
          - containerPort: 9100
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: XRP_CLIENT_PORT
            value: "9100"
          - name: REDIS_HOST
            value: "obridge-relay-db-redis-master"
          - name: RPC_URL
            value: "wss://s.altnet.rippletest.net:51233"
          - name: CONTRACT_ADDRESS
            value: ""
          - name: SYSTEM_CHAIN_ID
            value: "144"
          - name: CHAIN_ID
            value: ""
          - name: START_BLOCK
            value: "45926524"
          - name: DEV_MONITOR
            value: "false"
          - name: SERVER_URL_TRANSFER_OUT
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_out"
          - name: SERVER_URL_TRANSFER_IN
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_in"
          - name: SERVER_URL_CONFIRM
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_confirm"
          - name: SERVER_URL_REFUNDED
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_refunded"