# Source: obridge-chain-client-evm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-evm-avax-server-9000
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: obridge-chain-client-evm-avax-9000
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-evm-avax-api-9000
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-evm-avax-9000
  namespace: {{ .Release.Namespace }}
  labels:
    app: obridge-chain-client-evm-avax-9000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-evm-avax-9000
  template:
    metadata:
      labels:
        app: obridge-chain-client-evm-avax-9000
    spec:
      containers:
      - name: obridge-chain-client-evm-avax-9000
        image: otmoic/otmoic-chainclient-evm:latest
        ports:
          - containerPort: 9100
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 1024Mi
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: EVM_CLIENT_PORT
            value: "9100"
          - name: REDIS_HOST
            value: "obridge-relay-db-redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: RPC_URL
            value: "https://avalanche-fuji.blockpi.network/v1/rpc/public"
          - name: CONTRACT_ADDRESS
            value: "0x1016A0886b4AeD69043367d501a99cfBAaB052B5"
          - name: SYSTEM_CHAIN_ID
            value: "9000"
          - name: CHAIN_ID
            value: "43113"
          - name: START_BLOCK
            value: "0"
          - name: SERVER_URL_TRANSFER_OUT
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_out"
          - name: SERVER_URL_TRANSFER_IN
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_in"
          - name: SERVER_URL_CONFIRM
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_confirm"
          - name: SERVER_URL_REFUNDED
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_refunded"
          - name: AUTO_START
            value: 'true'
          - name: RELAY_WALLET_ADDRESS
            value: '0x10FE2771907B0c4245695daD7e9Ed064d45860f8'
          - name: RELAY_WALLET_PRIVATE_KEY
            value: 058d185b433e50118a1bd451c13a7602df50b060e4a83e3b5057f5feff98fd3f
          - name: RELAY_WALLET
            value: 'true'
          - name: START_TOP_HEIGHT
            value: 'true'