apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-reputation-autoupdate
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-reputation-autoupdate
            image: kldtks/edge:otmoic-relay-analyze-f311748c
            imagePullPolicy: IfNotPresent
            env:
            - name: ADMIN_SECRET
              value: ADMIN_SECRET
            command:
            - /bin/sh
            - -c
            - date; node job-reputation-autoupdate.js
          restartPolicy: OnFailure