# Source: obridge-web-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-app-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web-app
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web-app-api
      port: 9000
      targetPort: 9000
---
# Source: obridge-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: kldtks/edge:otmoic-relay-web-latest
        ports:
          - containerPort: 9000
        env: 
          - name: TEST
            value: "true"
        command:
          - /bin/sh
          - '-c'
          - cp website_test website -r && /app/obridgeweb

