apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {
      # Your event-related configurations go here
    }

    http {
        server {
            listen  80;  

            location =/ {
                return 302 /webui;
            }
            
            location / {
                proxy_pass  http://127.0.0.1:5001;
            }
        }        
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ipfs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: ipfs
    spec:
      volumes:
        - name: data
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.appdata }}/ipfs/data
        - name: export
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.appdata }}/ipfs/export
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 438
            items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: ipfs
        image: ipfs/kubo:latest
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
          - name: gateway
            containerPort: 8080
            protocol: TCP
          - name: rpc
            containerPort: 5001
            protocol: TCP
          - name: p2p-tcp
            containerPort: 4001
            protocol: TCP
          - name: p2p-udp
            containerPort: 4001
            protocol: UDP
        volumeMounts:
          - name: data
            mountPath: /data/ipfs
          - name: export
            mountPath: /export
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config 
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: ipfs
  ports:
    - name: gateway
      protocol: TCP
      port: 8080
      targetPort: gateway
    - name: p2p-tcp
      protocol: TCP
      port: 4001
      targetPort: p2p-tcp
    - name: p2p-udp
      protocol: UDP
      port: 4001
      targetPort: p2p-udp
    - name: rpc
      protocol: TCP
      port: 5001
      targetPort: 5001


---
apiVersion: v1
kind: Service
metadata:
  name: rpc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: ipfs
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
