userspace:
  appData: "/data/app-data"
  appCache: "/data/app-cache"
  userData: "/data/user-data"
workloads:
  librechat:
    replicaCount: 1
  librechat-meilisearch:
    replicaCount: 1
  librechat-mongodb:
    replicaCount: 1
  librechat-nginx-proxy:
    replicaCount: 1
