# Default values for merchant-app

# BFL (ByteTrade Framework Layer) configuration
bfl:
  username: '' # Will be populated by Olares during installation

# Application configuration
app:
  name: merchant
  version: '0.3.17'

# Resource configuration
resources:
  app:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 500m
      memory: 64Mi

  postgres:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Storage configuration
storage:
  size: 1Gi
