# Default values for merchant-app

# BFL (ByteTrade Framework Layer) configuration
bfl:
  username: '' # Will be populated by Olares during installation

# Application configuration
app:
  name: merchant
  version: '0.4'

# Resource configuration
resources:
  app:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 500m
      memory: 64Mi

  postgres:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Storage configuration
storage:
  size: 1Gi

# Service configuration
service:
  type: ClusterIP
  port: 6000
  targetPort: 6000

# Frontend configuration
frontend:
  image:
    repository: docker.io/magicpigdocker/images
    tag: merchant-front-0.22
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 800m
      memory: 1024Mi
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000

# DID Gateway Configuration
didGate:
  host: 'https://did-gate.mdogs.me'

# Local DID Cache Service Configuration
localDidCache:
  host: 'http://localhost:6002'
