apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-bootstrap
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: frappehrms
binaryData:
  login.html: {{ .Files.Get "files/login.html" | b64enc }}
  patch_nginx.py: {{ .Files.Get "files/patch_nginx.py" | b64enc }}
  create_site.py: {{ .Files.Get "files/create_site.py" | b64enc }}
  sitecustomize.py: {{ .Files.Get "files/sitecustomize.py" | b64enc }}
