{{- $secretName := printf "%s-secrets" .Release.Name -}}
{{- $redisPort := .Values.redis.port | default "6379" | toString -}}
{{- $redisUrl := printf "redis://%s:%s" (.Values.redis.host | toString) $redisPort -}}
{{- if .Values.redis.password -}}
{{- $redisUrl = printf "redis://:%s@%s:%s" (.Values.redis.password | toString) (.Values.redis.host | toString) $redisPort -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: frappehrms
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.olaresEnv.ADMIN_PASSWORD | quote }}
  DB_PASSWORD: {{ .Values.mariadb.password | quote }}
  REDIS_CACHE: {{ $redisUrl | quote }}
  REDIS_QUEUE: {{ $redisUrl | quote }}
