---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisperwebui-config
  namespace: {{ .Release.Namespace }}
data:
  whisper_type: "faster-whisper"
  CDN_HOST: "{{ .Values.downloadCdnURL | default "https://dc3p1870nn3cj.cloudfront.net" }}/models"
