---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nastools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastools
  template:
    metadata:
      labels:
        app: nastools
    spec:
      initContainers:
        - name: init-chmod-data
          image: 'busybox:latest'
          command:
            - sh
            - '-c'
            - |
              chown -R 1000:1000 /home
          resources: {}
          volumeMounts:
            - name: home
              mountPath: /home
          securityContext:
            runAsUser: 0
      containers:
      - env:
        - name: PGID
          value: "1000" 
        - name: PUID
          value: "1000" 
        - name: UMASK
          value: "002" 
        - name: NASTOOL_AUTO_UPDATE
          value: 'false'
        name: nastools
        image: kldtks/edge:backup-nas-tools-291
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /config
          name: nastools-config
        - mountPath: /home
          name: home
      volumes:
      - name: nastools-config
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/nastools/v2.8.3/
      - name: home
        hostPath:
          type: Directory
          path: {{ .Values.userspace.userData }}
        

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
